version: '3.8'
networks:
    eskull:
        driver: bridge
services:
    db:
        image: mysql:8.0
        container_name: eskull-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - eskull
    cache:
        image: redis:6.2
        container_name: eskull-cache
        restart: always
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

        networks:
            - eskull

    app:
        build:
            args:
                user: skull
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: eskull
        container_name: eskull-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - eskull
    nginx:
        image: nginx:1.19.6
        container_name: eskull-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - eskull
