version: '3.8'
networks:
    eskull:
        driver: bridge
services:
    db:
        image: mysql:8.0
        container_name: "eskull-db"
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "5432:5432"
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
            - ./docker-data/mysql:/var/lib/mysql
        networks:
            - eskull
    redis:
        image: redis:latest
        container_name: "eskull-redis"
        restart: always
        command: redis-server --save 20 1 --loglevel warning
        ports:
            - "6379:6379"
        volumes:
            - ./docker-data/redis:/data
        networks:
            - eskull

    app:
        build:
            args:
                user: skull
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: eskull
        container_name: "eskull-app"
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - eskull
    nginx:
        image: nginx:1.19.6
        container_name: "eskull-nginx"
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - eskull
